# 1
name: Movie Listing CI Workflow
# 2
on: [push]

# 3
jobs:
  build-and-test:
    name: Build and run tests
    # runs-on: ubuntu-latest
    runs-on: macos-latest # Switched to macOS
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run:
          echo API_KEY=\"$API_KEY\" > ./local.properties

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Generate apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk